version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # location of package.json
    schedule:
      interval: "weekly"  # or "daily", "monthly"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5
